.nix-helpers/termonad.nix
src/Termonad/App.hs
src/Termonad/Config.hs

This should probably be two (or three) PRs in principle, but I can't really be bothered splitting the work out into separate branches right now; more importantly it's well separated into its own commits.
I don't really understand the code base yet, so if any of this should have been implemented differently, let me know and I can make changes—what matters is getting the functionality.

Options for setting font size in device units and turning off the confirm-on-exit dialog

---

src/Termonad/App.hs
src/Termonad/Term.hs

This probably works. Passed my basic testing anyway.
The hardest part was deciding what to call `termClose` ... that was the best I could come up with, even though it's in the same module as `termExit`. Same deal with `quit` and `exit` actually—sorry about that, I'm not good at names.
Oh, and while I was at it I realised the config argument to `exit` was redundant, so I removed that (and renamed some arguments for consistency with the rest of the module).

Apply confirmClose setting to tabs too.

---

.nix-helpers/bare.nix
.nix-helpers/termonad-with-packages.nix
README.md
default.nix

This PR updates the documentation for the .nix files, as well as simplifying some of them.
@LSLeary would you be able to give this a quick look over and make sure everything is sane?  If you see anything that looks strange, please don't hesitate to open an issue or PR fixing it.

Update docs in nix files

---

src/Termonad/Term.hs
src/Termonad/Types.hs

Appears to successfully test the invariant of the `FocusList` `Focus` having the same as the actually focused gtk `Widget` as mentioned in #8 . Unfortunately, I was wrong about the widgets we are using having an `Eq` class. In order to make said class, I activated `StandaloneDeriving`. If that's a nono, we'll have to implement `Eq` for widgets some other way. Other ways I tried did not quite work and this seems to.
If the `FocusList` is empty (as when the program initially starts) the program would throw an exception. So if `getFLFocusItem` returns `Nothing` the invariant function simply returns `True` and continues on as normal. I did not check to see if the gtk object was also `Nothing` since I did not think it would matter (the program might already be crashed). I was worried initially …

TMState-FocusList Invariant test

---

src/Termonad/Gtk.hs
src/Termonad/Term.hs
src/Termonad/Types.hs

This PR refactors some of the code testing invariants for TMState.

Refactor some invariants

---

src/Termonad/Term.hs

Currently termonad starts a bash shell, whereas terminal emulators usually honour the per-user default set via `chsh` and read from `/etc/passwd` or `$SHELL`.
I also changed the fallback title from `"bash"` to the more agnostic `"shell"`, since `"bash"` might be wrong.
I left a note in the source about how we should probably be using gi-vte's `getUserShell`. I haven't done so because catching the exception it can throw seems like more of a pain than just reading the env var directly.

Use user's default shell

---

src/Termonad/App.hs
src/Termonad/Config.hs

What it says on the tin.
The change seemed to be very simple; perhaps I've missed some flow-on effect. It appears to work fine though.

Allow users to disable the menu with a config option.

---

.nix-helpers/stack-nix-shell.nix
README.md

This is for #42.
It also adds a short explanation of how to build on MacOS.  I don't have a mac to test this on myself, so if there are any problems in the documentation, please let me know.

Add comment explaining the gtk patch for getting things working on darwin.

---

src/Termonad/Term.hs

This PR fixes the problems with focus.
The two main problems are that `widgetSetFocusOnClick` needs to be set to `False` for all the widgets in the tab label bar, and that `widgetGrabFocus` doesn't seem to be sufficient, so `windowSetFocus` is also used.
This fixes #45 and #7 for me.  I'll go ahead and merge this in, but @LSLeary can you check that works on your machine as well?  I assume that this is working for @Grendel-Grendel-Grendel, but please let me know if not.

Fix focus problems

---

src/Termonad/Types.hs

This PR is just a few small fixes.

Some code formatting for invariant PR.

---

src/Termonad/Config.hs

@LSLeary I've added some documentation about how the cursor colors work.  Let me know if you notice any mistakes.

Add documentation for the cursor colors.

---

src/Termonad/Config.hs
src/Termonad/Config/Vec.hs

Clean up some more of the docs in Termonad.Config.

More doc cleanup

---

src/Termonad/Config.hs
src/Termonad/Config/Vec.hs
src/Termonad/Term.hs

Updating a little more of the documentation in `Termonad.Config`.

Add more documentation for termonad.

---

src/Termonad/Config/Colour.hs

Just another small documentation update.
I also removed the folding markers because I think it makes the file look too busy.  If the file is too big, then should refactor it and split it up into multiple files.

Small documentation update and remove fold markers.

---

src/Termonad/App.hs
src/Termonad/Types.hs
src/Termonad/XML.hs

This PR adds a menu option to change the font size at runtime.

Add a menu option to change the font size.

---

example-config/ExampleColourExtension.hs
src/Termonad/Config/Colour.hs
src/Termonad/Config/Vec.hs
termonad.cabal

This PR just adds functions for easily creating a Fin and IFin.

Add functions for easily creating a Fin and IFin

---

.nix-helpers/stack-fhs-env.nix
stack-lts-12.yaml
stack-lts-13.yaml

This updates the stack files to lts-13.3 and lts-12.26.

Update lts 13.3

---

.nix-helpers/nixpkgs.nix
.nix-helpers/stack-fhs-env.nix
.nix-helpers/stack-shell.nix
.nix-helpers/termonad-with-packages.nix
default.nix
shell.nix
stack-lts-13.yaml

Make some of the nix stuff a little simpler.  Mostly a refactoring.  No big changes in functionality.

Clean up nix stuff.

---

termonad.cabal

Small formatting update to the description sent from @Unrooted in #166.

Small update to the description in the cabal file.

---

.github/workflows/ci.yml
termonad.cabal

All dependencies work's with ghc-8.10

Allow build with newer GHC

---

.nix-helpers/nixpkgs.nix
Setup.hs
example-config/ExampleColourExtension.hs
example-config/ExampleGruvboxColourExtension.hs
example-config/ExampleSolarizedColourExtension.hs
src/Termonad/App.hs
src/Termonad/Config/Colour.hs
src/Termonad/Term.hs
src/Termonad/Types.hs
stack.yaml.lock

Hey, I ran hlint and fixed all the issues.  
There was one about duplication in `App.hs` which I *ignored*, maybe you want to have a look and check if you agree: 
it flags the following three lines:
https://github.com/cdepillabout/termonad/blob/e69e7ac5e8ce96cd5d4db020c6732a534f5781a6/src/Termonad/App.hs#L333-L335
But extracting that to a function which returns all arguments (they are needed further down) seemed like unnecessary to me

Fix hlint issues

---

src/Termonad/Config/Colour.hs

So I've noticed that [Termite](https://github.com/thestinger/termite) has [`[colors].highlight`](https://github.com/thestinger/termite/blob/master/config#L57) field available as an option to change the color of highlighted text. And since Termite and Termonad are both VTE-based I thought it should be possible for Termonad to have it as well.

add highlightFgColour and highlightBgColour to ColourConfig

---

.nix-helpers/nixpkgs.nix
.nix-helpers/overlays.nix
default.nix
shell.nix

This pr modifies vte of nixpkgs to enable sixel.
This is the same as the trial of @gelisam with sixel.

Bump vte to use sixel

---

glade/preferences.glade
src/Termonad/App.hs
src/Termonad/Lenses.hs
src/Termonad/Term.hs
src/Termonad/Types.hs

Add allowBold option

---

.github/workflows/ci.yml
.nix-helpers/overlays.nix
.nix-helpers/stack-shell.nix
CHANGELOG.md
flake.lock
flake.nix
stack.yaml
stack.yaml.lock
termonad.cabal

This PR updates the Stackage resolver and Nixpkgs version that Termonad uses by default.

Update Stackage and Nixpkgs

---

termonad.cabal

This pull request removes unused packages.

Remove unused packages

---

.github/workflows/ci.yml
.gitignore
CHANGELOG.md
README.md
src/Termonad.hs
src/Termonad/App.hs
src/Termonad/Cli.hs
src/Termonad/PreferencesFile.hs
src/Termonad/Types.hs
termonad.cabal

Add a CLI argument parser

---

CHANGELOG.md
src/Termonad/App.hs
src/Termonad/Gtk.hs
stack.yaml
stack.yaml.lock
termonad.cabal

I am opening this PR in continuation of this: https://github.com/cdepillabout/termonad/pull/228.
Closes https://github.com/cdepillabout/termonad/issues/165

Use embedded icon - Part 3

---

CHANGELOG.md
src/Termonad/App.hs
src/Termonad/XML.hs
termonad.cabal

Also, hide menu bar action for creating new window, since it hasn't been fully implemented yet.

Bump termonad from 4.5.0.0 to 4.6.0.0
