cdepillabout/termonad

.nix-helpers/termonad-with-packages.nix

Recompilation is a bit of a mess atm; it didn't work at all on my system (not even using the `running-termonad.nix` file with nix-shell, though in retrospect I guess `--pure` would have done it) so I had a look into it.
It turns out that nix-patched dyre looks to the `$NIX_GHC` env var for a ghc, then looks in the `$PATH` if that's unset. Without a wrapper setting `$NIX_GHC` correctly for termonad, it will either find nothing there, or as it seems happened in my case, use the `$NIX_GHC` crafted for xmonad instead. So I took inspiration from the way xmonad is packaged and wrote a secondary derivation that wraps termonad to give it a correct `$NIX_GHC` without running in a nix-shell or polluting the system environment.
A comment in the file itself has a little more exposition.
I've left my …

Fixed recompilation for termonad built through .nix-helpers/termonad-with-packages.nix

---

src/Termonad/App.hs

This PR removes the use of the `min-width` style property, which appears to not be supported on older(?) versions of GTK.
@lehins, could you try compiling Termonad this PR and make sure it works for you?  If it does, I'll go ahead and merge it in.
Hopefully fixes #21.

Try removing the min-width style.

---

.gitignore
src/Termonad/Config.hs
src/Termonad/Term.hs
termonad.cabal
termonad.cabal~
test/readme/README.lhs

A quick fix that resolves issue #3 partially. I was unsure exactly how `getCursorColor` was getting its value from the config so I didn't touch that, though I added an exception list value to the relevant datatype and default.
I found that I had to add `.:/` which was three characters in order to successfully select the entire URL. If this is something unique to me perhaps there is something else weird going on.

URL wordwise selection fix

---

README.md
src/Termonad/App.hs
src/Termonad/Config.hs

This changes the font size setting to be  a sumtype to better reflect the two options.
@LSLeary originally implemented the pixel-based font-size option.

Change fontsize to be a sumtype.

---

src/Termonad/Config.hs
src/Termonad/Term.hs
termonad.cabal

With one big problem ... I can't set the background colour? `terminalSetColors` is meant to do it but it doesn't. I tried doubling up and using `terminalSetColorBackground` too—didn't change anything. Am I doing something wrong or is it a bug in `gi-vte`?

Implemented basic colour configuration

---

.nix-helpers/nixpkgs.nix
.nix-helpers/termonad.nix
src/Termonad.hs
src/Termonad/Config.hs
src/Termonad/Term.hs
termonad.cabal

> Type-safe palette representation:
>  * Example/default values for each palette entry.
>  * Function to generate colour cubes.
>  * Heaps of vector and matrix utilities.
>  * Organisation via text folding in Config.hs.
I got a bit carried away writing this one. type-combinators didn't have as many handy utility functions as I'd been expecting, though it did have enough supporting machinery to easily justify its use. It was also lacking a few instances we could do with. For now they're orphans derived/declared in `Termonad.Config`, but I've submitted PRs upstream; hopefully they're accepted and the orphans can be dropped as soon as there's a hackage version including the changes. The written utilities are also quite general, so they too hopefully will be accepted upstream and dropped …

Type-safe palette

---

src/Termonad/App.hs
src/Termonad/Config.hs
src/Termonad/Term.hs

Allow the user to configure that the tab bar is always shown, never shown, or shown only if there's more than one tab.
From my light testing this works as is, but I've left some TODO comments on a few parts that could do with some feedback and changes. Let me know what you think and I'll clean it up.

Make the tab bar's presence configurable.

---

src/Termonad/Term.hs

`(<&>)` was missing to be imported in `Termonad.Term`.

fix missing import.

---

.nix-helpers/nixpkgs.nix
stack-lts-12.yaml

This PR adds the correct version of type-combinators to be used with
stack.  This if for #36.

Make sure to use the latest version of type-combinators in lts-12.

---

src/Termonad.hs
src/Termonad/Config.hs
src/Termonad/Term.hs

I'm using the `CursorBlinkMode` type and constructors directly as configuration values, and reexporting them from the Termonad module.
I don't really know how VTE is going to treat `AnotherCursorBlinkMode x` values. I tried a few to see if it would crash, but it seems like it just ignores the setting. Maybe the constructor should be excluded from the reexport?

Allow CursorBlinkMode configuration.

---

README.md
example-config/ExampleColourExtension.hs
src/Termonad/Config/Colour.hs
termonad.cabal

This adds some docs for the ColourExtension.  It also moves an example of using the ColourExtension from the Haddocks to an actual example file.

Update docs for ColourConfig

---

src/Termonad/App.hs
src/Termonad/FocusList.hs
src/Termonad/Term.hs
src/Termonad/Types.hs
stack-lts-12.yaml
termonad.cabal
test/Test/FocusList.hs
test/Test/FocusList/Invariants.hs

This overhauls `FocusList` to use `Sequence` instead of `Intmap`. After I updated documentation, it passes all tests. Resolves issue #64, excepting that I have not added big O growth rates. according to my innovative benchmarking techinque of "opening as many tabs as possible and watching the results in htop."
Many functions were scrapped because they no longer serve any purpose, along with their documentation. One function which has changed significantly is `insertFL` which no longer has an unsafe counterpart. Instead, it behaves according to how `insertAt` from `Sequence` does. That is, if an index is out of bounds, it will be inserted at the "nearest" available index. Look to the code examples for demonstration. In general, I have made the `FocusList` methods behave like their …

FocusList implemented with Sequences

---

src/Termonad/App.hs

Paste's hotkey was typo'd/overlapping with copy's use of ctrl-shift-c. I changed it to ctrl-shift-v.

Fix paste hotkey

---

.travis.yml
README.md
example-config/ExampleSolarizedColourExtension.hs
termonad.cabal

An example of how to configure Termonad to use the Solarized palette.

Added Solarized example

---

.nix-helpers/nixpkgs.nix
.nix-helpers/termonad-with-packages.nix

This PR makes it so that Termonad can see GTK icons when compiling with the wrapper.
Now the tab close button should actually be an icon.

Make icons work

---

src/Termonad/Config/Vec.hs

With this change, termonad builds on both GHC 8.4.4 and GHC 8.6.3.
Closes: #97

Remove type applications from sing in instance declarations

---

.nix-helpers/stack-nix-shell.nix
.travis.yml
stack-lts-13.yaml
stack.yaml
termonad.cabal

This switches Termonad over to use LTS-13 when compiled with `stack`.
This is the continuation of the GHC-8.6 support added by @clinty.

Get Termonad compatible with LTS-13

---

.nix-helpers/nixpkgs.nix
.nix-helpers/stack-fhs-env.nix
.nix-helpers/stack-shell.nix
default.nix
stack-lts-13.yaml

Update to use the latest version of nixpkgs.

Get building with nixpkgs 19.03

---

.nix-helpers/termonad-with-packages.nix

Try to fix the pixbuf problem from #107.

Try to fix the pixbuf problem.

---

example-config/ExampleColourExtension.hs
example-config/ExampleSolarizedColourExtension.hs
src/Termonad/App.hs
src/Termonad/Config.hs
src/Termonad/Config/Colour.hs

This PR fixes the bug in #29 with not being able to set the background color for a terminal if the palette was set.
In #110, @dakotaclemenceplaza figured out that this was caused by not setting any value for the alpha channel of an RGBA color.
This PR uses the fix from #110 and simplifies some of the logic for setting colors.
Fixes #29

Fix foreground and background colors

---

.travis.yml
CHANGELOG.md
README.md
example-config/ExampleColourExtension.hs
example-config/ExampleSolarizedColourExtension.hs
src/Termonad/Config/Colour.hs
termonad.cabal

This PR fix #112
It seems that there is no direct way to get the RGB components back from an AlphaColour. So I needed to work around, which feels kind of hacky. See the comments for more informations.
Also the functions used to convert RGB components to word8 are not exposed from the Colour library. So I had to copy pieces of code from the Internal module to make sure it's going to behave in a consistent way.

Change Colour to AlphaColour

---

src/Termonad/App.hs
src/Termonad/Term.hs

This PR closes #31. I did my best to split the functions into parts. It's not clear to me why the function passed to modifyMVar needs to return an IO action called straight after. Why not call it from inside ?

Refactor createTerm

---

README.md

On Ubuntu 18.04, trying to install the dependency list and then running `stack install` resulted in
`setup: The pkg-config package 'libpcre2-8' is required but it could not be found.`
After installing `libpcre2-dev` as well I was able to install using stack and run termonad.

Update Ubuntu / Debian dependencies

---

.nix-helpers/stack-fhs-env.nix

When running stack in an FHS env, stack needs to be version 1.9.3.
If you use stack > 2.1, you run into the following bug:
https://github.com/commercialhaskell/stack/issues/5000
I don't have time to figure out this bug right now, so this is just a quick work-around.

When running stack in an FHS env, stack needs to be version 1.9.3.

---

CHANGELOG.md
src/Termonad/App.hs
src/Termonad/Prelude.hs
src/Termonad/Types.hs
src/Termonad/XML.hs
termonad.cabal

Here is my take for a basic preference dialog #82
I did not spend much time trying to make the dialog looks good. I've focused on making the feature works. 
I was confused to see the settings related to the current font in `tmStateFontDesc` and in `tmStateConfig/options/fontConfig`. It is not clear to me why it needs to be that way. 
Anyway, so when the user validates the dialog, I decided to update the information at both places. Note that it is not the case when the font size is changed using the menu. In this case only `tmStateFontDesc` seems to be updated. 
I'm quite happy how it went, tell me what you think about it.

Preferences dialog

---

CHANGELOG.md
src/Termonad/Term.hs

This PR adds a very simple context menu to Termonad #12.
For now I've put only copy/paste items. But adding existing actions to the menu is pretty straight forward. 
I've worked a bit on adding an action to open an url in a navigator. It's not as easy at it seems for two reasons:
- Some annotations in Vte functions are missing but I sent a PR to fix it haskell-gi/haskell-gi#265
- It requieres to cast `EventButton` to `Event` to be able to call `terminalMatchCheckEvent` and it's not currently supported by haskell-gi. This issue haskell-gi/haskell-gi#109 is exactly the same as the one I run on. There is a workaround decribed in the issue thought.

Add a context menu

---

CHANGELOG.md
src/Termonad/App.hs

In #129, @ssbothwell reported that there was a stray one-pixel white border around the GtkNotebook.
@Reasonable-Solutions provided an easy way to debug these types of problems, as well as the solution to this particular problem.
This PR sets the Notebook so it doesn't have the one-pixel border.

Get rid of the one-pixel border around the GtkNotebook.

---

example-config/ExampleSolarizedColourExtension.hs

This PR does the following:
* Properly sets Solarized background colours for Termonad using `backgroundColour`
* Swaps 2 Solarized dark colours `base02` and `base03` into their correct positions

Corrected Solarized backgrounds

---

.nix-helpers/nixpkgs.nix
CHANGELOG.md
shell.nix
src/Termonad/Config/Colour.hs
src/Termonad/Term.hs
stack.yaml
termonad.cabal

Nixpkgs was recently updated to use the latest haskell-gi versions: https://github.com/NixOS/nixpkgs/pull/95434.
Termonad needs a slight update to work with the latest haskell-gi version.

Get termonad working with latest version of nixpkgs and haskell-gi

---

CHANGELOG.md
src/Termonad/Term.hs
termonad.cabal

Tested by building using nix-build under NixOS and executing result/bin/termonad.

Issue #170; added Preferences to context menu.

---

CHANGELOG.md
glade/preferences.glade
src/Termonad/App.hs
src/Termonad/Lenses.hs
src/Termonad/Term.hs
src/Termonad/Types.hs
termonad.cabal

Added the option boldIsBright which is set to False by default. If set to True in termonad.hs this will lead to bright bold fonts. 
This solves the issue with the unreadable blue text on dark background since blue text is almost always used together with bold fonts. 
I would recommend to even set boldIsBright to True by default.

Option boldIsBright added

---

CHANGELOG.md
README.md
src/Termonad/App.hs
src/Termonad/Term.hs
termonad.cabal

This PR adds 2 shortcuts: `<Ctrl>Page_Up` (switch to previous page) and `<Ctrl>Page_Down` (switch to next page). Inspired by gnome-terminal and xfce4-terminal.

add shortcuts to switch to the prev/next page

---

README.md

I don't hang out on the #termonad room on IRC, so I don't want users to think that they could get help directly from me there.
However, if there is someone that wants to officially take over helping using on the freenode #termonad room, I'd be happy to start directing people there as well.  (Although I should probably add a section to the readme about where to get help.)

Update README.md and remove irc #termonad badge

---

.github/workflows/ci.yml
.nix-helpers/nixpkgs.nix
stack-nightly.yaml
stack.yaml
termonad.cabal

This also makes sure the doctests aren't run with `-rtsopts -N`, because this was causing them to segfault.

Update Stackage and Nixpkgs versions

---

CHANGELOG.md
src/Termonad/App.hs
src/Termonad/Config/Colour.hs
src/Termonad/PreferencesFile.hs
termonad.cabal

Fix #189
To be able to read old versions of the configuration file, we first read it as a JSON object then mconcat it with the `defaultConfigOptions`.
Note that we lose a bit of type safety here as any valid yaml file will now be accepted by termonad. But I think it is ok.

add support for old preference file

---

CHANGELOG.md
example-config/ExamplePaperColourColourExtension.hs
termonad.cabal

This adds an example of the PaperColor theme as used by myself.
Tested successfully locally.

example-config: added PaperColor

---

.github/workflows/ci.yml
.nix-helpers/nixpkgs.nix
.nix-helpers/overlays.nix
.nix-helpers/termonad-with-packages.nix
default.nix
flake.lock
flake.nix
stack.yaml
stack.yaml.lock
termonad.cabal

Also bump stackage resolver to lts-18.9.

Add flake for nix users

---

.github/workflows/ci.yml
.nix-helpers/overlays.nix
.nix-helpers/stack-shell.nix
flake.lock
flake.nix
stack-nightly.yaml

This PR switches the Nix files for Termonad to build with GHC-9.0.2 by default.
This is in preparation for getting Termonad working in Nixpkgs, which is currently in the process of switching from GHC-8.10.7 to GHC-9.0.2 as the default Haskell compiler: https://github.com/NixOS/nixpkgs/pull/160733

Build with GHC-9.0.2 with Nix by default

---

README.md

Small change to the README to clarify how to install Termonad with Nix.
This closes https://github.com/cdepillabout/termonad/issues/196.

Clarify how to install with Nix

---

.github/workflows/ci.yml
CHANGELOG.md
Setup.hs
glade/preferences.glade
src/Termonad/App.hs
src/Termonad/Gtk.hs
src/Termonad/Lenses.hs
src/Termonad/Term.hs
src/Termonad/Types.hs
termonad.cabal

Hi, this pr adds the option of enable-sixel.
However, even if the option is enabled, the image of sixel is not shown. The vte supporting sixel may not be released.
https://gitlab.gnome.org/GNOME/vte/-/issues/253

Add enableSixel

---

.hlint.yaml
README.md
src/Termonad/Term.hs

This PR adds the ability to open a URL by right-clicking on it.
URLs also get underlined when you mouse over them.

Open URLs by right-clicking on them

---

src/Termonad/Config.hs

Haddock documentation was obsolete, so I updated it to be fully valid Haskell term according to current Termonad API.

Make code example up-to-date

---

.hlint.yaml
src/Termonad/App.hs
src/Termonad/Cli.hs
src/Termonad/Config/Colour.hs
src/Termonad/Gtk.hs
src/Termonad/IdMap.hs
src/Termonad/IdMap/Internal.hs
src/Termonad/Keys.hs
src/Termonad/Lenses.hs
src/Termonad/PreferencesFile.hs
src/Termonad/Prelude.hs
src/Termonad/Term.hs
src/Termonad/Types.hs
src/Termonad/XML.hs
termonad.cabal

This is the initial PR for adding support for controlling multiple Windows within a single Termonad Application.
This PR just contains a large refactoring of the `TMState` data type, which adds the ability to track multiple GTK Windows, in the data type `TMWindow`.
However, there is no actual code supporting the creation of multiple windows, so this PR is mostly just a reorganization.  It should not have changed any actual functionality in Termonad.
Related to #6

Add support for controlling multiple windows in one Termonad process

---

.github/workflows/ci.yml
.nix-helpers/simple-cabal-shell.nix
src/Termonad/App.hs
src/Termonad/Config/Colour.hs
src/Termonad/Gtk.hs
src/Termonad/Term.hs
src/Termonad/Types.hs

Small cleanup

---

CHANGELOG.md
src/Termonad/App.hs
src/Termonad/Config.hs
src/Termonad/Preferences.hs
src/Termonad/Preferences/File.hs
src/Termonad/Types.hs
src/Termonad/XML.hs
termonad.cabal

Also, rename `Termonad.PreferencesFile` to `Termonad.Preferences.File`.

Split out Preferences-related functions from Termonad.App to Termonad.Preferences

---

CHANGELOG.md
README.md
src/Termonad.hs
src/Termonad/App.hs
src/Termonad/Startup.hs
termonad.cabal

You will no longer be able to get `defaultMain` from `Termonad.App`.
However, you should instead be getting it from the top-level `Termonad` module.

Move defaultMain and startWithCliArgs to Termonad.Startup module

---

src/Termonad/App.hs
src/Termonad/Types.hs
src/Termonad/Window.hs
termonad.cabal

This PR does some small refactoring.  A new Termonad.Window module is created to hold functions that operate on a specific Window.  (As opposed to Termonad.App, which now only holds functions that operate on the whole Termonad application.)
This is more preliminary refactoring for https://github.com/cdepillabout/termonad/issues/6

Split Window-specific functions out of Termonad.App into new Termonad.Window module

---

.nix-helpers/nixos-vm.nix
.nix-helpers/overlays.nix
.nix-helpers/simple-cabal-shell.nix
flake.lock

This bumps the default compiler in Nix to GHC-9.4, as well as updating the nixpkgs-unstable pin to the latest version.

Bump nixpkgs-unstable and default compiler in Nix to ghc94
